Vagrant.configure("2") do |config|
  # 基础设置
  config.vm.box = "generic/centos7"

  # 获取 IP 列表并分割为数组
  ip_list = ENV["VM_IP_LIST"]&.split(",")
  host_list = ENV["VM_HOST_LIST"]&.split(",")
  group_name = ENV["VM_GROUP_NAME"]
  bridge = ENV["VM_BRIDGE"]
  gateway = ENV["VM_GATEWAY"]
  dns = ENV["VM_DNS"]
  password = ENV["VM_PASS"]
  memory = ENV["VM_MEMORY"]
  cpus = ENV["VM_CPUS"]
  disks = ENV["VM_DISKS"]&.split(",")

  # 定义虚拟机名称和 IP 地址范围
  ip_list.each_with_index do |ip, index|
    config.vm.define host_list[index] do |node|
      # 设置主机名
      node.vm.hostname = host_list[index]

      # 配置桥接网络，并为每台虚拟机分配不同的 IP
      node.vm.network "public_network", ip: ip, bridge: bridge

      # 配置网关和 DNS,shell中读取环变量，需要通过env参数进行传递后，才能识别
      node.vm.provision "shell", inline: <<-SHELL, env: { "GATEWAY" => gateway, "DNS" => dns, "PASSWORD" => password }
        # 配置网关
        echo "GATEWAY=${GATEWAY}" >> /etc/sysconfig/network
        systemctl restart network

        # 配置 DNS
        echo "nameserver ${DNS}" > /etc/resolv.conf

        # 设置 root 密码
        echo "root:${PASSWORD}" | chpasswd

        # 修改 SSH 配置文件，允许密码登录
        sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
        sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

        # 重启 SSH 服务
        systemctl restart sshd
      SHELL


      # 配置虚拟机资源
      node.vm.provider "virtualbox" do |vb|
        vb.name = host_list[index]  # 设置虚拟机名称
        vb.memory = memory        # 设置内存为 4G
        vb.cpus = cpus             # 设置 CPU 为 2 核
        vb.customize ["modifyvm", :id, "--groups", group_name] # 设置虚拟机的分组
        disks.each_with_index do |size, i|
          # 需要盘点磁盘是否创建过，否则二次启动时，会报磁盘已存在，创建失败
          disk_path = "./#{host_list[index]}-disk#{i + 1}.vdi"
          unless File.exist?(disk_path)
            vb.customize ["createhd", "--filename", disk_path, "--size", size] # 10GB = 10240MB
          end
          vb.customize ["storageattach", :id, "--storagectl", "SATA Controller",
                        "--port", i+1, "--device", 0, "--type", "hdd", "--medium", disk_path]
        end
      end
    end
  end
end
