version: "3.8"

services:
  mysql-master01:
    image: mysql:5.7
    container_name: mysql-master01
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./master01/master.cnf:/etc/mysql/conf.d/master.cnf
    ports:
      - 3306:3306

  mysql-master02:
    image: mysql:5.7
    container_name: mysql-master02
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./master02/master.cnf:/etc/mysql/conf.d/master.cnf
    ports:
      - 3307:3306

  mysql-slave01:
    image: mysql:5.7
    container_name: mysql-slave01
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./slave01/slave.cnf:/etc/mysql/conf.d/slave.cnf
    ports:
      - 3308:3306

  mysql-slave02:
    image: mysql:5.7
    container_name: mysql-slave02
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./slave02/slave.cnf:/etc/mysql/conf.d/slave.cnf
    ports:
      - 3309:3306