# 集群验证
# docker exec -it ndb_management ndb_mgm -e show
# 数据验证
# docker exec -it ndb_mysqld1 mysql -uroot -p123456 -e "CREATE DATABASE test01;"
# docker exec -it ndb_mysqld1 mysql -uroot -p123456 -e "SHOW DATABASES;"
# docker exec -it ndb_mysqld2 mysql -uroot -p123456 -e "SHOW DATABASES;"
version: '3'
networks:
  my_cluster:
    driver: bridge
services:
  # 服务名，在同一个网络下的docker容器之间可以通过服务名访问，
  # 所以我在创建容器以及后面的配置文件中没有指定IP
  ndb_management:
    image: mysql/mysql-cluster:8.0
    # 容器名，docker exec等命令用的
    container_name: ndb_management
    # 容器启动命令
    # command会传给entrypoint.sh并启动不同的服务
    # 这个就只是启动的 ~ $ ndb_mgmd --ndb-nodeid=1 ...
    command: [
      'ndb_mgmd',
      '--reload',
      '--initial'
    ]
    # 容器卷，用来配置集群
    # 集群配置文件为config.cnf
    # 对应到容器里面的/etc/mysql-cluster.cnf，至于为什么，大家可以去看下镜像的源码
    # 配置/etc/my.cnf，可以在当前容器执行ndb_mgm -e show查看集群状态，不添加配置，会查询失败，只能去其他节点查询
    volumes:
      - ./ndb_management/config.cnf:/etc/mysql-cluster.cnf
      - ./ndb_management/my.cnf:/etc/my.cnf
      - ./ndb_management/data:/var/lib/mysql
    ports:
      - "1186:1186"
    # 指定网络
    networks:
      - my_cluster
  
  ndb_data1:
    image: mysql/mysql-cluster:8.0
    container_name: ndb_data1
    command: [
      'ndbd'
    ]
    volumes:
      - ./ndb_data1/my.cnf:/etc/my.cnf
      - ./ndb_data1/data:/var/lib/mysql
    networks:
      - my_cluster

  ndb_data2:
    image: mysql/mysql-cluster:8.0
    container_name: ndb_data2
    command: [
      'ndbd'
    ]
    volumes:
      - ./ndb_data2/my.cnf:/etc/my.cnf
      - ./ndb_data2/data:/var/lib/mysql
    networks:
      - my_cluster
  
  ndb_mysqld1:
    image: mysql/mysql-cluster:8.0
    container_name: ndb_mysqld1
    command: [
      'mysqld',
      '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mycluster
    volumes:
      - ./ndb_mysqld1/my.cnf:/etc/my.cnf
      - ./ndb_mysqld1/data:/var/lib/mysql
    networks:
      - my_cluster
    ports:
      - "3326:3306"
    depends_on:
      - ndb_management
      - ndb_data1
      - ndb_data2

  ndb_mysqld2:
    image: mysql/mysql-cluster:8.0
    container_name: ndb_mysqld2
    command: [
      'mysqld',
      '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./ndb_mysqld2/my.cnf:/etc/my.cnf
      - ./ndb_mysqld2/data:/var/lib/mysql
    networks:
      - my_cluster
    ports:
      - "3327:3306"
    depends_on:
      - ndb_management
      - ndb_data1
      - ndb_data2